# 自动检查仓库更新开关
Auto: false
# 推送的群聊列表
Gruop: []
# 仓库更新检查Cron表达式
Cron: "0 */10 * * * *"

# Github个人token
# 获取方式：https://github.com/settings/tokens
GithubToken: ""

# 关注的仓库路径
# 格式: 用户名/仓库名
# 如: github.com/DenFengLai/DF-Plugin 则填 DenFengLai/DF-Plugin
# 优先检查Github，如果未找到则检查Gitee
GithubList:
  - yoimiya-kokomi/miao-plugin
  - DenFengLai/DF-Plugin