# 自动检查仓库更新开关
Auto: false
# 推送的群聊列表
Gruop: []
# 仓库更新检查Cron表达式
Cron: "0 */10 * * * *"

# 自动获取已安装的插件地址并监听
AutoPath: false

# 自定义关注的Github仓库路径
# 格式: 用户名/仓库名:分支名(可选)
# 如: github.com/DenFengLai/DF-Plugin 则填 DenFengLai/DF-Plugin
# 支持分支 DenFengLai/DF-Plugin:dev
GithubList:
  - yoimiya-kokomi/miao-plugin
  - DenFengLai/DF-Plugin

# 自定义关注的Gitee仓库路径
# 格式: 用户名/仓库名:分支名(可选)
# 如: gitee.com/DenFengLai/DF-Plugin 则填 DenFengLai/DF-Plugin
GiteeList:
  - DenFengLai/poke

# 排除的仓库路径
# 用于忽略一些不希望被监听的插件
Exclude: []

# Gitee个人token
# 可用于解除API每小时60次限制
# 获取方式：https://gitee.com/profile/personal_access_tokens
GiteeToken: ""

# Github个人token
# 可用于解除API每小时60次限制
# 获取方式：https://github.com/settings/tokens
GithubToken: ""
