# 戳一戳开关
chuo: true

# 戳一戳图片设置
# 1：柴郡表情包 
# 2：丛雨表情包 
# 3：诗歌剧表情包 
# 4：柚子厨表情包 
# 5：小南梁表情包
# 6：小鲨鱼古拉
# 7：甘城猫猫
# 8: 龙图
# 9：满穗表情包
# 10: 猫猫虫表情
# 11：纳西妲表情
# 12；心海表情
# 13：fufu表情
# 14: ATRI表情包
# 15: 绫地宁宁表情包
# 16: 永雏塔菲表情包
# 0：自定义图片（自行在resources/poke/default中添加）
# all: 随机类型
chuoType: 1

# 戳一戳随机类型黑名单
Black:
  - default

# 原神关键词发图
ys: true