# 联系主人开关
open: true
# 联系主人CD 单位：秒 填0关闭cd
cd: 300
# 是否发送全部主人 0：仅发送首个主人 1：发送全部主人 
# 填主人账号可以指定发送某个主人
Master: 0
# 指定某个Bot发送 为0时为触发Bot
BotId: 0
# 是否发送触发者的头像（微信请关闭此项）
sendAvatar: true
# 发送成功是否回复主人QQ号
replyQQ: true

# 违禁词，当消息包含下列内容将不会发送给主人
banWords:
  - 垃圾
  - 你妈
  - nm
  - 月吗
  - 🈷️吗
  - 🈷吗
  - 约吗
# 禁用的用户，不允许该用户联系主人
banUser:
  - 10086
# 禁用的群聊，不允许通过该群联系主人
banGroup:
  - 114514